build="cargo build --release"
test="cargo test --release"
test-mmap="cargo test --features mmap --release"
test-hf="cargo test --features hf-hub --release"
test-nodef="cargo test --no-default-features --release"
clippy = "cargo clippy --all-features"
clippy-fix = "cargo clippy --all-features --fix --allow-dirty"
format = "cargo fmt --all -- --check"
format-fix = "cargo fmt --all"
