build="cargo build --release -p statembed"
test="cargo test --release -p statembed"
test-rayon="cargo test --features rayon --release -p statembed"
test-hf="cargo test --features hf-hub --release -p statembed"
test-nodef="cargo test --no-default-features --release -p statembed"
clippy = "cargo clippy --all-features"
clippy-fix = "cargo clippy --all-features --fix --allow-dirty"
format = "cargo fmt --all -- --check"
format-fix = "cargo fmt --all"
